name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        suite: [unit, integration]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('server_py/requirements.txt') }}

      - name: Install Node dependencies
        run: npm ci

      - name: Install Python dependencies
        run: pip install -r server_py/requirements.txt

      - name: Run ${{ matrix.suite }} tests
        run: npm run test:${{ matrix.suite }}

  scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('server_py/requirements.txt') }}

      - name: Install Node dependencies
        run: npm ci

      - name: Install Python dependencies
        run: pip install -r server_py/requirements.txt

      - name: Run security scans
        run: npm run scan

  notify:
    needs: [test, scan]
    if: failure() && env.SLACK_WEBHOOK_URL != ''
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "CI pipeline failed for *${{ github.repository }}* on `${{ github.ref }}`. See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
